name: Build tsschecker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set Up Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool pkg-config \
                                libcurl4-openssl-dev libfragmentzip-dev \
                                libgeneral-dev libirecovery-dev libplist-dev \
                                libssl-dev

    - name: Configure Project
      run: |
        ./autogen.sh  # Ensure that autogen.sh exists and is executable
        ./configure --prefix=/usr

    - name: Build Project
      run: make

    - name: Run Tests
      run: make test  # Assuming there's a 'make test' target in the Makefile

    - name: Install Project
      run: sudo make install

    - name: Cleanup
      run: make clean
